# Site settings
title: Raymond Blog
SEOTitle: 刘永霖的博客 | Raymond Blog
header-img: img/home-bg.jpg
email: nfsysuliuyonglin@gmail.com
description: "关于数据与算法，健身与美食 | 刘永霖，Python & Linux Lover，Software Engineer，UI Designer | 这里是 @Raymond 刘永霖 的个人博客，与你一起发现更大的世界。"
keyword: "刘永霖,Raymond, 博客, 大数据, matlab, c++, python, R语言, 人工智能"
url: "https://HappayRaymond.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username:     liu-yong-lin-37
zhihu_username:     liu-yong-lin-37
github_username:    HappyRaymond
# twitter_username:   huxpro
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: Raymond

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
# ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
# ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "刘永霖，从嵌入式到机器学习，编程语言:python c/c++, linux系统 <br> Raymond, from embedded to machine learning, programming language: python c/c++, linux system"
# sidebar-avatar: https://github.com/Huxpro.png # use absolute URL, seeing it's used in both `/` and `/about/`

sidebar-avatar: /img/raymond/human.jpg

# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    {
    #     title: "Su",
    #     href: "http://su.gallery/"
    # },{
        title: "jerry",
        href: "https://ng-fukgin.github.io/"
    },{
        title: "Sherry Woo",
        href: "https://sherrywoo.me/"
    }
]
